version: '3'
services:
  prestamos-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - prestamos-db

  prestamos-db:
    image: "h2database/h2:latest"
    ports:
      - "9092:9092"
    environment:
      - H2_CONSOLE_ENABLED=true
      - H2_DATABASE_NAME=prestamos
      - H2_DATABASE_USERNAME=sa
      - H2_DATABASE_PASSWORD=password
    volumes:
      - ./data:/data
